<a href="https://colab.research.google.com/github/AnaghaAj/MACHINE_LEARNING_LAB/blob/main/EXPERIMENT1b_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><center>Experiment 1.B</center></h1> 

Date______________________-

Aim: To perform a review of python and matrix operations using Numpy programming               


## Numpy

- Used for scientific computing
- Helps to create/ manage N-dimensional array

In [ ]:
import numpy as np #importing numpy package

In [ ]:
x = np.array([1,2,3,4]) #creating numpy array from list

In [ ]:
print(x)

[1 2 3 4]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
print(x.shape) #printing the dimensoin of the array

(4,)


In [ ]:
y = np.array([[1,2],[3,4]])

In [ ]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [ ]:
z = np.array([[1+0.j,2+5.j]])  #printing thr dimension of the numpy array

In [ ]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [ ]:
a = np.zeros((2,3)) #creating numpy array of zeros , of dimension (2,3)

In [ ]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
b = np.ones((2,3), dtype=int) #creating numpy array of ones , of dimension (2,3) and integer type

In [ ]:
print(b)

[[1 1 1]
 [1 1 1]]


In [ ]:
d = np.eye(3) ## identity matrix

In [ ]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e = np.arange(10) ##similar to Range function

In [ ]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
e = np.arange(12, 21)

In [ ]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [ ]:
e = np.arange(5,20,3)

In [ ]:
print(e)

[ 5  8 11 14 17]


In [ ]:
f = np.linspace(1,20,7) ## It create intervals

In [ ]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [ ]:
g = np.random.random((3,4))

In [ ]:
print(g)

[[0.76569656 0.41910349 0.80824715 0.81440212]
 [0.90242021 0.34820756 0.83762195 0.26478698]
 [0.7222503  0.19027176 0.60580345 0.86248711]]


In [ ]:
h = np.random.random((3,4)) #creating a numpy array having dimension (3,4) with random elements

In [ ]:
print(h.reshape(2,2,3)) #reshaping the (3,4) array to (2,2,3)

[[[0.65961394 0.66853994 0.22580269]
  [0.44762129 0.66074186 0.57047389]]

 [[0.17034335 0.40193131 0.56505872]
  [0.63687196 0.86033868 0.60140624]]]


In [ ]:
x = np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [ ]:
print(x[-1])

11


In [ ]:
x.resize(3,4)

In [ ]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(x[-1,-1])

11


In [ ]:
print(x[2][3])

11


In [ ]:
y = np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [ ]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
print(y[10:15])

[11 12 13 14 15]


In [ ]:
print(y[-5:])

[21 22 23 24 25]


In [ ]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [ ]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [ ]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [ ]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [ ]:
print(y[:,-1])

[ 5 10 15 20 25]


In [ ]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [ ]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [ ]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [ ]:
print(a>3)

[False False False  True  True]


In [ ]:
a = np.arange(0,4).reshape((2,2))

In [ ]:
b = np.eye(2)

In [ ]:
print(a*b) ##Wrong

[[0. 0.]
 [0. 3.]]


In [ ]:
print(np.dot(a,b)) ##Matrix multiplication

[[0. 1.]
 [2. 3.]]


In [ ]:
x = np.arange(1,10).reshape(3,3)

In [ ]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(x.sum())

45


In [ ]:
print(x.sum(axis=0))

[12 15 18]


In [ ]:
print(x.sum(axis=1))

[ 6 15 24]


In [ ]:
x = np.arange(1,19).reshape(3,3,2)

In [ ]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [ ]:
x = np.arange(1,10).reshape(3,3)

In [ ]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [ ]:
print(x.max(axis=0))

[7 8 9]


In [ ]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
